import { neon } from '@neondatabase/serverless';
import crypto from 'node:crypto';
type User={id:string;name:string;email:string;phone:string;password_hash:string;verified:boolean;verification_hash:string|null;verification_expires:number|null;pin_hash:string;balance:number;created_at:number};
const sql=neon(process.env.DATABASE_URL as string);
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
const phoneNorm=(v:string)=>v.replace(/[^0-9+]/g,'');
const emailNorm=(v:string)=>v.trim().toLowerCase();
const publicUser=(u:User)=>({id:u.id,name:u.name,email:u.email,phone:u.phone,verified:u.verified,balance:u.balance});
let schemaReady:Promise<void>|null=null;
async function ensureSchema(){if(schemaReady)return schemaReady;schemaReady=(async()=>{await sql`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,phone TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,verified BOOLEAN NOT NULL DEFAULT FALSE,verification_hash TEXT,verification_expires BIGINT,pin_hash TEXT NOT NULL,balance NUMERIC NOT NULL DEFAULT 250000,created_at BIGINT NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,subtitle TEXT NOT NULL,amount NUMERIC NOT NULL,incoming BOOLEAN NOT NULL,created_at BIGINT NOT NULL,counterparty TEXT,demo_reference TEXT,demo_sender_id TEXT,demo_recipient_id TEXT,demo_sender_name TEXT,demo_recipient_name TEXT)`;await sql`CREATE INDEX IF NOT EXISTS transactions_user_created_idx ON transactions(user_id,created_at DESC)`;})();return schemaReady}
async function findUser(identifier:string){const q=identifier.includes('@')?emailNorm(identifier):phoneNorm(identifier);const rows=identifier.includes('@')?await sql`SELECT * FROM users WHERE lower(email)=${q} LIMIT 1`:await sql`SELECT * FROM users WHERE phone=${q} LIMIT 1`;return rows[0] as User|undefined}
async function history(userId:string){return sql`SELECT id,title,subtitle,amount,incoming,created_at AS "createdAt",counterparty,demo_reference AS "demoReference",demo_sender_id AS "demoSenderId",demo_recipient_id AS "demoRecipientId",demo_sender_name AS "demoSenderName",demo_recipient_name AS "demoRecipientName" FROM transactions WHERE user_id=${userId} ORDER BY created_at DESC`}
async function balanceFor(userId:string,base:number){const rows=await sql`SELECT COALESCE(SUM(CASE WHEN incoming THEN amount ELSE -amount END),0) AS delta FROM transactions WHERE user_id=${userId}`;return Number(base)+Number(rows[0]?.delta||0)}
async function sendVerification(email:string,code:string){const key=process.env.RESEND_API_KEY;if(!key)return false;const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({from:'Bay U <onboarding@resend.dev>',to:[email],subject:'Your Bay U verification code',html:'<h2>Verify your Bay U account</h2><p>Your verification code is:</p><h1>'+code+'</h1><p>This code expires in 10 minutes.</p>'})});return res.ok}
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function fail(message:string,status=400){return json({message},status)}
async function body(req:Request){try{return await req.json()}catch{return {}}}
export async function GET(req:Request){await ensureSchema();const u=new URL(req.url),path=u.pathname.replace(/^\/api\/?/,'');if(path==='health')return json({ok:true,database:true});if(path==='recipient'){const user=await findUser(u.searchParams.get('identifier')||'');if(!user||!user.verified)return fail('Bay U recipient not found.',404);return json({id:user.id,name:user.name,phone:user.phone,email:user.email})}if(path.startsWith('account/')){const id=path.split('/')[1];const rows=await sql`SELECT * FROM users WHERE id=${id} LIMIT 1`;const user=rows[0] as User|undefined;if(!user)return fail('Account not found.',404);return json({user:{...publicUser(user),balance:await balanceFor(id,user.balance)},transactions:await history(id)})}return fail('Route not found.',404)}
export async function POST(req:Request){await ensureSchema();const u=new URL(req.url),path=u.pathname.replace(/^\/api\/?/,''),b:any=await body(req);
if(path==='register'){const name=String(b.name||'').trim(),email=emailNorm(String(b.email||'')),phone=phoneNorm(String(b.phone||'')),password=String(b.password||''),pin=String(b.pin||'');if(name.length<2)return fail('Enter your full name.');if(!/^\S+@\S+\.\S+$/.test(email))return fail('Enter a valid email address.');if(!/^0[789][01]\d{8}$/.test(phone.replace(/^\+?234/,'0')))return fail('Enter a valid Nigerian phone number.');if(password.length<8)return fail('Password must be at least 8 characters.');if(!/^\d{4}$/.test(pin))return fail('Transaction PIN must be 4 digits.');if(await findUser(email))return fail('An account with this email already exists.',409);const byPhone=await sql`SELECT id FROM users WHERE phone=${phone} LIMIT 1`;if(byPhone.length)return fail('An account with this phone number already exists.',409);const id=crypto.randomUUID(),code=String(crypto.randomInt(100000,1000000)),now=Date.now();await sql`INSERT INTO users(id,name,email,phone,password_hash,verified,verification_hash,verification_expires,pin_hash,balance,created_at) VALUES(${id},${name},${email},${phone},${hash(password)},false,${hash(code)},${now+600000},${hash(pin)},250000,${now})`;const sent=await sendVerification(email,code);if(!sent){await sql`UPDATE users SET verified=true,verification_hash=NULL,verification_expires=NULL WHERE id=${id}`;const row=(await sql`SELECT * FROM users WHERE id=${id}`)[0] as User;return json({ok:true,user:publicUser(row),message:'Account created. Email delivery is unavailable, so this demo account was verified automatically.'})}return json({ok:true,userId:id,message:'Verification code sent to your email.'})}
if(path==='verify'){const rows=await sql`SELECT * FROM users WHERE id=${String(b.userId||'')} LIMIT 1`;const user=rows[0] as User|undefined;if(!user)return fail('Account not found.',404);if(user.verified)return json({ok:true,user:publicUser(user)});if(!user.verification_expires||Date.now()>Number(user.verification_expires))return fail('That verification code has expired.');if(hash(String(b.code||''))!==user.verification_hash)return fail('Incorrect verification code.');await sql`UPDATE users SET verified=true,verification_hash=NULL,verification_expires=NULL WHERE id=${user.id}`;return json({ok:true,user:publicUser({...user,verified:true})})}
if(path==='login'){const user=await findUser(String(b.identifier||''));if(!user||user.password_hash!==hash(String(b.password||'')))return fail('Incorrect email/phone or password.',401);if(!user.verified)return fail('Please verify your email before logging in.',403);return json({ok:true,user:{...publicUser(user),balance:await balanceFor(user.id,user.balance)}})}
if(path==='transactions'){const userId=String(b.userId||'');if(!(await sql`SELECT id FROM users WHERE id=${userId}`).length)return fail('Account not found.',404);if(!b.title)return fail('Transaction title is required.');const id=crypto.randomUUID();await sql`INSERT INTO transactions(id,user_id,title,subtitle,amount,incoming,created_at,counterparty) VALUES(${id},${userId},${String(b.title)},${String(b.subtitle||'Bay U simulation • Just now')},${Number(b.amount)||0},${!!b.incoming},${Number(b.createdAt)||Date.now()},NULL)`;return json({ok:true,id})}
if(path==='transfer'){const senderId=String(b.senderId||''),amount=Number(b.amount)||0;if(amount<=0)return fail('Enter a valid amount.');const sr=await sql`SELECT * FROM users WHERE id=${senderId} LIMIT 1`;const sender=sr[0] as User|undefined;if(!sender)return fail('Sender account not found.',404);if(sender.pin_hash!==hash(String(b.pin||'')))return fail('Incorrect transaction PIN.',401);const recipient=await findUser(String(b.recipientIdentifier||''));if(!recipient||!recipient.verified)return fail('Bay U recipient not found.',404);if(recipient.id===senderId)return fail('You cannot transfer to yourself.');const sb=await balanceFor(senderId,sender.balance);if(sb<amount)return fail('Insufficient demo balance.');const reference='BU-DEMO-'+Date.now().toString(36).toUpperCase(),createdAt=Date.now();await sql`INSERT INTO transactions(id,user_id,title,subtitle,amount,incoming,created_at,counterparty,demo_reference,demo_sender_id,demo_recipient_id,demo_sender_name,demo_recipient_name) VALUES(${crypto.randomUUID()},${senderId},${'Transfer to '+recipient.name},${'Sent to '+recipient.name+' • Demo'},${amount},false,${createdAt},${recipient.id},${reference},${senderId},${recipient.id},${sender.name},${recipient.name}),(${crypto.randomUUID()},${recipient.id},${'Transfer from '+sender.name},${'Received from '+sender.name+' • Demo'},${amount},true,${createdAt},${senderId},${reference},${senderId},${recipient.id},${sender.name},${recipient.name})`;return json({ok:true,amount,reference,recipient:{id:recipient.id,name:recipient.name,phone:recipient.phone,email:recipient.email},sender:{id:sender.id,name:sender.name,phone:sender.phone,email:sender.email},senderBalance:await balanceFor(senderId,sender.balance),message:'Bay U demo transfer recorded. No real money moved.'})}
if(path==='security/password'){const rows=await sql`SELECT * FROM users WHERE id=${String(b.userId||'')} LIMIT 1`;const user=rows[0] as User|undefined;if(!user)return fail('Account not found.',404);if(user.password_hash!==hash(String(b.currentPassword||'')))return fail('Current password is incorrect.',401);if(String(b.newPassword||'').length<8)return fail('New password must be at least 8 characters.');await sql`UPDATE users SET password_hash=${hash(String(b.newPassword))} WHERE id=${user.id}`;return json({ok:true})}
if(path==='security/pin'){const rows=await sql`SELECT * FROM users WHERE id=${String(b.userId||'')} LIMIT 1`;const user=rows[0] as User|undefined;if(!user)return fail('Account not found.',404);if(user.pin_hash!==hash(String(b.currentPin||'')))return fail('Current PIN is incorrect.',401);if(!/^\d{4}$/.test(String(b.newPin||'')))return fail('New PIN must be 4 digits.');await sql`UPDATE users SET pin_hash=${hash(String(b.newPin))} WHERE id=${user.id}`;return json({ok:true})}
return fail('Route not found.',404)}
export async function PUT(req:Request){await ensureSchema();const u=new URL(req.url),path=u.pathname.replace(/^\/api\/?/,''),b:any=await body(req);if(path.startsWith('profile/')){const id=path.split('/')[1],name=String(b.name||'').trim(),phone=phoneNorm(String(b.phone||''));if(name.length<2)return fail('Enter a valid name.');if(!/^0[789][01]\d{8}$/.test(phone.replace(/^\+?234/,'0')))return fail('Enter a valid Nigerian phone number.');const dup=await sql`SELECT id FROM users WHERE phone=${phone} AND id<>${id} LIMIT 1`;if(dup.length)return fail('That phone number is already in use.',409);await sql`UPDATE users SET name=${name},phone=${phone} WHERE id=${id}`;const row=(await sql`SELECT * FROM users WHERE id=${id}`)[0] as User|undefined;if(!row)return fail('Account not found.',404);return json({ok:true,user:{...publicUser(row),balance:await balanceFor(row.id,row.balance)}})}return fail('Route not found.',404)}
